### ISSUE TITLE
Bug - Feature - BloodType DAO - CRUD

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/bloodbankapp-core#1]
Scenario: As a user, I need to save, update, findAll, findOne blood details.
Bug: In  BloodTypeDetailDAO - in all CRUD methods, you did not execute Query to update the records in DB.

![image](https://user-images.githubusercontent.com/22638364/126290209-ee19d8a4-e170-4e57-a181-778ef13a1872.png)

**Comment by hemalatha3001** [comment]
solved
